### root access

GET http://localhost:8000


### Login API endpoint

POST http://localhost:8000/api/v1/Login
Content-Type: application/json

{
    "email": "db7@gmail.com",
    "password" : "pass123"
   
}

### ADD Product API

POST http://localhost:8000/api/v1/product
Content-Type: application/json

{
    "name" : "Dalla Sabun",
    "price":"2.5"
    


}
